In [698]:
import numpy as np

In [699]:

#the wavelengths of K_alpha1 and K_beta1 for Mo42 are 
lambda_alpha = 0.7114 * 10**(-10) #m
lambda_beta = 0.6323  * 10**(-10) #m
#for NaCl , the d (distance between the planes of the crystal) is defined as
d = 2.82 * 10**(-10) #m  
#from the class book 

In [700]:
def arcsin(x):
    return np.rad2deg(np.arcsin(x))

In [701]:
# Calculate the theoretical values of the angles 
theta_theory = np.array([])
for n in [3,2,1]:
    theta_alpha = arcsin(n*lambda_alpha/(2*d))
    theta_beta = arcsin(n*lambda_beta/(2*d))
    theta_theory = np.append(theta_alpha,theta_theory)
    theta_theory = np.append(theta_beta,theta_theory)

In [702]:
# Running calibration.c as
# root calibration.c > outputs/txt/calibration.txt,
# we get the experimental values as: 
theta_exp       = np.array([6.60858, 7.73428, 13.4170, 15.0649, 20.0906, 22.6886])
sigma_theta_exp = np.array([7.33008e-02,5.50475e-02,6.00465e-02,5.37266e-02,5.55138e-02,3.89494e-02])

In [703]:
theta_exp, sigma_theta_exp, theta_theory #Will use these in macros

(array([ 6.60858,  7.73428, 13.417  , 15.0649 , 20.0906 , 22.6886 ]),
 array([0.0733008, 0.0550475, 0.0600465, 0.0537266, 0.0555138, 0.0389494]),
 array([ 6.43695807,  7.24629098, 12.95700727, 14.61185045, 19.65342192,
        22.23487353]))

# Plotting the experimental values against the theoritical values, we get 
'''
Processing plotangles.c...
 FCN=16.7945 FROM MIGRAD    STATUS=CONVERGED      52 CALLS          53 TOTAL
                     EDM=3.50175e-09    STRATEGY= 1      ERROR MATRIX ACCURATE 
  EXT PARAMETER                                   STEP         FIRST   
  NO.   NAME      VALUE            ERROR          SIZE      DERIVATIVE 
   1  p0           9.89902e-01   4.26597e-03   3.09820e-06  -4.30818e-02
   2  p1          -2.64330e-01   6.37784e-02   4.63205e-05  -3.52675e-03
'''
#where p0 is the slope and p1 is the intercept of the y axis.

In [704]:
a = 0.989902
b = 0.26433

#In order to do calibrate our values, we will put the experimental thetas in the function,
def calibrate(theta):
    return 0.989902*theta - 0.26433

#and get the calibrated values as:
calibrated_theta = calibrate(theta_exp)
calibrated_theta

array([ 6.27751656,  7.39184924, 13.01718513, 14.64844464, 19.62339512,
       22.19516052])

In [705]:
#Calculate the sigma of the calibrated data

N = len(theta_exp)
theta_mean = np.mean(theta_exp)
sum = 0
for i in range(N): 
        sum += (0.989902*theta_exp[i] - theta_mean)**2

sigma_calibrated_theta = np.sqrt(sum/(N-1))

#as referenced in the statistical book of the class.

sigma_calibrated_theta

6.37932861650604

In [706]:
# The uncertainty of the wavelength will be calculated as follows in the macro files; 
sigma_wavelength = np.sqrt( (2* d * np.cos(calibrated_theta) * sigma_calibrated_theta)**2 )

#Go to linefits folder and run it with the command :

chmod +x execution.sh
./execution.sh

#results are in the outputs folder 


------------------------------------------------------------------------------

15kV

****************************************
Minimizer is Minuit / Migrad
Chi2                      =      5.50454
NDf                       =            6
Edm                       =  6.99549e-21
NCalls                    =           41
p0                        =      1037.05   +/-   153.28      
p1                        =      -81.666   +/-   12.4816     

Approximate value of Planck's constant: 6.30773e-34
Actual value of Planck's constant: 6.626e-34

------------------------------------------------------------------------------

18kV

 FCN=41.8981 FROM MIGRAD    STATUS=CONVERGED      38 CALLS          39 TOTAL
                     EDM=4.67553e-19    STRATEGY= 1      ERROR MATRIX ACCURATE 
  EXT PARAMETER                                   STEP         FIRST   
  NO.   NAME      VALUE            ERROR          SIZE      DERIVATIVE 
   1  p0           2.39467e+03   1.20992e+02   1.55555e-02  -5.70974e-12
   2  p1          -1.58505e+02   8.35753e+00   1.07449e-03   3.30641e-11

Approximate value of Planck's constant: 6.36225e-34
Actual value of Planck's constant: 6.626e-34

------------------------------------------------------------------------------

21kV

 FCN=59.5916 FROM MIGRAD    STATUS=CONVERGED      33 CALLS          34 TOTAL
                     EDM=3.71671e-18    STRATEGY= 1      ERROR MATRIX ACCURATE 
  EXT PARAMETER                                   STEP         FIRST   
  NO.   NAME      VALUE            ERROR          SIZE      DERIVATIVE 
   1  p0           2.76923e+03   1.07464e+02   2.39009e-02  -4.21404e-10
   2  p1          -1.53887e+02   6.38966e+00   1.42111e-03  -6.97486e-09

Approximate value of Planck's constant: 6.23166e-34
Actual value of Planck's constant: 6.626e-34

------------------------------------------------------------------------------

24kV

 FCN=238.035 FROM MIGRAD    STATUS=CONVERGED      34 CALLS          35 TOTAL
                     EDM=6.06295e-19    STRATEGY= 1      ERROR MATRIX ACCURATE 
  EXT PARAMETER                                   STEP         FIRST   
  NO.   NAME      VALUE            ERROR          SIZE      DERIVATIVE 
   1  p0           5.66371e+03   1.01609e+02   7.37216e-02  -1.11803e-10
   2  p1          -2.90300e+02   5.89840e+00   4.27954e-03  -1.89277e-09

Approximate value of Planck's constant: 6.56898e-34
Actual value of Planck's constant: 6.626e-34

------------------------------------------------------------------------------

27kV

 FCN=50.1862 FROM MIGRAD    STATUS=CONVERGED      34 CALLS          35 TOTAL
                     EDM=8.44109e-20    STRATEGY= 1      ERROR MATRIX ACCURATE 
  EXT PARAMETER                                   STEP         FIRST   
  NO.   NAME      VALUE            ERROR          SIZE      DERIVATIVE 
   1  p0           4.78392e+03   1.33349e+02   4.43967e-02   2.68074e-11
   2  p1          -2.06793e+02   6.96160e+00   2.31777e-03   5.44149e-10

Approximate value of Planck's constant: 6.23241e-34
Actual value of Planck's constant: 6.626e-34

------------------------------------------------------------------------------

30kV

 FCN=12.3275 FROM MIGRAD    STATUS=CONVERGED      35 CALLS          36 TOTAL
                     EDM=7.9035e-19    STRATEGY= 1      ERROR MATRIX ACCURATE 
  EXT PARAMETER                                   STEP         FIRST   
  NO.   NAME      VALUE            ERROR          SIZE      DERIVATIVE 
   1  p0           5.79943e+03   3.32306e+02   3.78559e-02   5.23204e-11
   2  p1          -2.17742e+02   1.56685e+01   1.78495e-03   1.06983e-09

Approximate value of Planck's constant: 6.01476e-34
Actual value of Planck's constant: 6.626e-34


In [707]:
linefit_slopes      = [ 1037.05, 2394.67 ,2769.23 ,5663.71 ,4783.92 ,5799.43 ] #nm
linefit_y_intercept = [ -81.666,-158.505,-153.887,-290.300 ,-206.793,-217.742]

#and the uncertainties as

sigma_linefit_slopes = [153.28, 120.992 , 107.464, 101.609 ,133.349,  332.306] #nm
sigma_linefit_y_intercept = [12.4816,8.35751,6.38964,5.89840 ,6.96160,15.6685]
 
 # p0 is the slope, p1 is the y-intercept. p1 has the unit [impulse/second], and since p0 = y/x
 # it has an unit imp/s / nm = imp/sm * 1e9 .
 # to account for this, we multiply p0 and sp0 by 1e9 to get the correct units

linefit_slopes = np.array(linefit_slopes) * 1e9 #m
sigma_linefit_slopes = np.array(sigma_linefit_slopes) * 1e9 #m


In [708]:
# We need to find the lambda_min values, which is the x-intercept of each graph. 
# We can use the fact that p_0 * x + p_1 = y to find it, by setting y = 0 . 

lambda_min = np.array([])

for i in [5,4,3,2,1,0]:
    p_0 = linefit_slopes[i]
    p_1 = linefit_y_intercept[i]
    lambda_min = np.append(-p_1/p_0,lambda_min)

lambda_min # in meters

array([7.87483728e-11, 6.61907486e-11, 5.55703210e-11, 5.12561554e-11,
       4.32266844e-11, 3.75454139e-11])

In [709]:
# Since what we are after is f_max, we will use the formula f_max = c/lambda_min
c = 2.997*10**8     #m/s
f_max = c/lambda_min # m.s/m = s^-1 = Hz
f_max # Hz 

array([3.80579292e+18, 4.52782309e+18, 5.39316662e+18, 5.84710261e+18,
       6.93321739e+18, 7.98233309e+18])

In [717]:
# We will plot the energies ( E = q_electron * V_acc ) of the electrons against f_max of each fit 
# to find the Planck's Constant h at the end, since h = E/f_max, the slope.  

energy_V = np.array([])  
q_electron = 1.60217662 * 10**(-19)
V_acc = [15,18,21,24,27,30] * 10**3  # convert from kV to V
for i in [5,4,3,2,1,0]:   
     energy_V = np.append(q_electron * V_acc[i] * 10**3,energy_V)


#energy_V is in eV
energy_V 

array([2.40326493e-15, 2.88391792e-15, 3.36457090e-15, 3.84522389e-15,
       4.32587687e-15, 4.80652986e-15])

In [711]:
#We also need the uncertainties of the datapoints themselves. In order to do this calculation we will use 
# the poisson sigma calculation 

c = 2.997*10**8

sigma_lambda_min = np.array([])
sigma_f_max = np.array([])
for i in [5,4,3,2,1,0]:   
    
    a = linefit_slopes[i]
    b = linefit_y_intercept[i]
    sigma_a = sigma_linefit_slopes[i]
    sigma_b = sigma_linefit_y_intercept[i]

    sigma_lambda_min_i = (-b/a) * np.sqrt((sigma_a/a)**2 + (sigma_b/b**2)**2)
    sigma_f_max_i      = (-a/b) * np.sqrt((sigma_a/a)**2 + (sigma_b/b**2)**2) * c

    sigma_lambda_min = np.append(sigma_lambda_min_i,sigma_lambda_min)
    sigma_f_max      = np.append(sigma_f_max_i,sigma_f_max)


sigma_lambda_min,sigma_f_max

(array([1.16402470e-11, 3.34439594e-12, 2.15653930e-12, 9.19560911e-13,
        1.20493935e-12, 2.15137933e-12]),
 array([5.62556001e+17, 2.28775675e+17, 2.09294738e+17, 1.04899928e+17,
        1.93262716e+17, 4.57393450e+17]))

In [715]:
#Food for thought 
# Why only K-lines are observed when we bombard electrons to the metal?
# This is actually interesting, since outershells of the atom is more easier to be ionized 
# I think this has two reasons 
# 1) Even if the number of electrons ionized in the outershells such as L and M are more, it is more likely for an electron to fill the vacancy
# shell in the K shell, since it is closer to the nucleus, the energy difference is bigger.  
# 2) Since the energy difference is smaller in the outershells, it is probable that the geiger-muller tube does not count when a
# X-Ray is emitted from the outershells, because, maybe? its energy is not enough to ionize the gas in the tube.

3.5630848173860554e+36
